replicaCount: 3

image:
  repository: stefanprodan/podinfo
  tag: "6.4.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 9898

ingress:
  enabled: true
  className: "nginx"
  host: my-gitops-app.local

metrics:
  enabled: true
